# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mnorm_D_arma <- function(mu, Sig_diag, Sig_LT) {
    .Call('_fold_mnorm_D_arma', PACKAGE = 'fold', mu, Sig_diag, Sig_LT)
}

unorm_D_arma <- function(mu, sigma) {
    .Call('_fold_unorm_D_arma', PACKAGE = 'fold', mu, sigma)
}

makeHellingerAvg <- function(theta, d, n) {
    .Call('_fold_makeHellingerAvg', PACKAGE = 'fold', theta, d, n)
}

makeuHellingerAvg <- function(theta, n) {
    .Call('_fold_makeuHellingerAvg', PACKAGE = 'fold', theta, n)
}

risk_cpp <- function(c, Delta, omega) {
    .Call('_fold_risk_cpp', PACKAGE = 'fold', c, Delta, omega)
}

rand_index <- function(c1, c2) {
    .Call('_fold_rand_index', PACKAGE = 'fold', c1, c2)
}

minimize_risk_cpp <- function(c, Delta, omega) {
    .Call('_fold_minimize_risk_cpp', PACKAGE = 'fold', c, Delta, omega)
}

ldmvnorm_arma <- function(y, mu, Sigma, d) {
    .Call('_fold_ldmvnorm_arma', PACKAGE = 'fold', y, mu, Sigma, d)
}

ldunorm_arma <- function(y, mu, sigma_sq) {
    .Call('_fold_ldunorm_arma', PACKAGE = 'fold', y, mu, sigma_sq)
}

maketau <- function(Pi, y, mu, Sigma) {
    .Call('_fold_maketau', PACKAGE = 'fold', Pi, y, mu, Sigma)
}

makeutau <- function(Pi, y, mu, Sigma) {
    .Call('_fold_makeutau', PACKAGE = 'fold', Pi, y, mu, Sigma)
}

lmaketau <- function(Pi, y, mu, Sigma) {
    .Call('_fold_lmaketau', PACKAGE = 'fold', Pi, y, mu, Sigma)
}

