#' FOLD elbow plot
#'
#' Creates the elbow plot for choosing a clustering point estimate with FOLD.
#' @param tree Matrix of candidate clusterings generated by hierarchical clustering on Delta.
#' Each row index is the number of clusters.
#' @param Delta An nxn symmetric matrix of pairwise Hellinger distances.
#' @importFrom graphics points axis
#' @return An elbow plot showing the average Hellinger separation for each candidate clustering.
#' @details The elbow plot computes the total within-cluster pairwise Hellinger distances for each candidate clustering. A heuristic for
#' choosing the number of clusters is to identify the candidate at which the plot bends.
#' @export
#' @useDynLib foldcluster
elbow <- function(tree, Delta) {
  max.k <- nrow(tree)
  tv <- c()
  h_bar <- sum(Delta[lower.tri(Delta)])
  for (k in 1:max.k){
    wss <- c()
    for (h in 1:k) {
      Delta_h <- Delta[tree[k,]==h, tree[k,]==h]
      wss[h] <- sum(Delta_h[lower.tri(Delta_h)])
    }
    tv[k] <- sum(wss)/h_bar
  }
  plot(x=1:max.k, y = tv,
       type = "l",
       xlab = "No. of Clusters",
       main = "Elbow Plot")
  axis(1, at = 1:max.k)
  points(x=1:max.k, y = tv)
}
