# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mnorm_D_arma <- function(mu, Sig_diag, Sig_LT) {
    .Call('_foldcluster_mnorm_D_arma', PACKAGE = 'foldcluster', mu, Sig_diag, Sig_LT)
}

unorm_D_arma <- function(mu, sigma) {
    .Call('_foldcluster_unorm_D_arma', PACKAGE = 'foldcluster', mu, sigma)
}

makeHellingerAvg <- function(theta, d, n) {
    .Call('_foldcluster_makeHellingerAvg', PACKAGE = 'foldcluster', theta, d, n)
}

makeuHellingerAvg <- function(theta, n) {
    .Call('_foldcluster_makeuHellingerAvg', PACKAGE = 'foldcluster', theta, n)
}

risk_cpp <- function(c, Delta, omega) {
    .Call('_foldcluster_risk_cpp', PACKAGE = 'foldcluster', c, Delta, omega)
}

rand_index <- function(c1, c2) {
    .Call('_foldcluster_rand_index', PACKAGE = 'foldcluster', c1, c2)
}

minimize_risk_cpp <- function(c, Delta, omega) {
    .Call('_foldcluster_minimize_risk_cpp', PACKAGE = 'foldcluster', c, Delta, omega)
}

ldmvnorm_arma <- function(y, mu, Sigma, d) {
    .Call('_foldcluster_ldmvnorm_arma', PACKAGE = 'foldcluster', y, mu, Sigma, d)
}

ldunorm_arma <- function(y, mu, sigma_sq) {
    .Call('_foldcluster_ldunorm_arma', PACKAGE = 'foldcluster', y, mu, sigma_sq)
}

maketau <- function(Pi, y, mu, Sigma) {
    .Call('_foldcluster_maketau', PACKAGE = 'foldcluster', Pi, y, mu, Sigma)
}

makeutau <- function(Pi, y, mu, Sigma) {
    .Call('_foldcluster_makeutau', PACKAGE = 'foldcluster', Pi, y, mu, Sigma)
}

lmaketau <- function(Pi, y, mu, Sigma) {
    .Call('_foldcluster_lmaketau', PACKAGE = 'foldcluster', Pi, y, mu, Sigma)
}

